# Generated by Django 5.1.2 on 2024-10-21 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yt_title', models.CharField(max_length=100, verbose_name='Youtube название')),
                ('yt_link', models.URLField(max_length=255, verbose_name='YouTube')),
                ('ig_title', models.CharField(max_length=100, verbose_name='Instagram название')),
                ('ig_link', models.URLField(max_length=255, verbose_name='Instagram')),
                ('wt_title', models.CharField(max_length=100, verbose_name='Whatsapp название')),
                ('wt_link', models.URLField(max_length=255, verbose_name='Watsapp')),
                ('email_link', models.EmailField(max_length=255, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Ссылки',
                'verbose_name_plural': 'Ссылки',
            },
        ),
    ]
