# Generated by Django 5.1.2 on 2024-10-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='ig_link',
            field=models.URLField(max_length=255, verbose_name='Instagram ссылка'),
        ),
        migrations.AlterField(
            model_name='links',
            name='wt_link',
            field=models.URLField(max_length=255, verbose_name='Watsapp ссылка'),
        ),
        migrations.AlterField(
            model_name='links',
            name='yt_link',
            field=models.URLField(max_length=255, verbose_name='YouTube ссылка'),
        ),
    ]
