# Generated by Django 5.1.2 on 2024-10-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutCompany', models.CharField(max_length=255, verbose_name='О компании')),
                ('aboutCompany_ru', models.CharField(max_length=255, null=True, verbose_name='О компании')),
                ('aboutCompany_en', models.CharField(max_length=255, null=True, verbose_name='О компании')),
                ('aboutProject', models.CharField(max_length=255, verbose_name='О компании')),
                ('aboutProject_ru', models.CharField(max_length=255, null=True, verbose_name='О компании')),
                ('aboutProject_en', models.CharField(max_length=255, null=True, verbose_name='О компании')),
                ('video_link', models.URLField(max_length=255, verbose_name='Ссылка на видео')),
            ],
            options={
                'verbose_name': 'О компании',
                'verbose_name_plural': 'О компании',
            },
        ),
    ]
