# Generated by Django 5.1.2 on 2024-10-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutnuran', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcompany',
            name='aboutCompany_kg',
            field=models.CharField(max_length=255, null=True, verbose_name='О компании'),
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='aboutProject_kg',
            field=models.CharField(max_length=255, null=True, verbose_name='О компании'),
        ),
    ]
