# Generated by Django 5.1.2 on 2024-10-17 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutnuran', '0002_aboutcompany_aboutcompany_kg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutcompany',
            old_name='aboutCompany_kg',
            new_name='aboutCompany_ky',
        ),
        migrations.RenameField(
            model_name='aboutcompany',
            old_name='aboutProject_kg',
            new_name='aboutProject_ky',
        ),
    ]
