# Generated by Django 5.1.2 on 2024-10-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutnuran', '0003_rename_aboutcompany_kg_aboutcompany_aboutcompany_ky_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcompany',
            name='aboutProject',
            field=models.CharField(max_length=255, verbose_name='О проекте'),
        ),
        migrations.AlterField(
            model_name='aboutcompany',
            name='aboutProject_en',
            field=models.CharField(max_length=255, null=True, verbose_name='О проекте'),
        ),
        migrations.AlterField(
            model_name='aboutcompany',
            name='aboutProject_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='О проекте'),
        ),
        migrations.AlterField(
            model_name='aboutcompany',
            name='aboutProject_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='О проекте'),
        ),
    ]
