# Generated by Django 5.1.2 on 2024-10-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutnuran', '0004_alter_aboutcompany_aboutproject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcompany',
            name='aboutCompany',
            field=models.TextField(max_length=255, verbose_name='О компании'),
        ),
        migrations.AlterField(
            model_name='aboutcompany',
            name='aboutCompany_en',
            field=models.TextField(max_length=255, null=True, verbose_name='О компании'),
        ),
        migrations.AlterField(
            model_name='aboutcompany',
            name='aboutCompany_ky',
            field=models.TextField(max_length=255, null=True, verbose_name='О компании'),
        ),
        migrations.AlterField(
            model_name='aboutcompany',
            name='aboutCompany_ru',
            field=models.TextField(max_length=255, null=True, verbose_name='О компании'),
        ),
        migrations.AlterField(
            model_name='aboutcompany',
            name='aboutProject',
            field=models.TextField(verbose_name='О проекте'),
        ),
        migrations.AlterField(
            model_name='aboutcompany',
            name='aboutProject_en',
            field=models.TextField(null=True, verbose_name='О проекте'),
        ),
        migrations.AlterField(
            model_name='aboutcompany',
            name='aboutProject_ky',
            field=models.TextField(null=True, verbose_name='О проекте'),
        ),
        migrations.AlterField(
            model_name='aboutcompany',
            name='aboutProject_ru',
            field=models.TextField(null=True, verbose_name='О проекте'),
        ),
    ]
