# Generated by Django 5.1.2 on 2024-10-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта для получения заказов')),
            ],
            options={
                'verbose_name': 'Почта',
                'verbose_name_plural': 'Почта',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('number', models.CharField(max_length=255, verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Заказ на звонок',
                'verbose_name_plural': 'Заказы на звонок',
            },
        ),
    ]
