# Generated by Django 5.1.2 on 2024-10-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Галерея')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('description_ru', models.CharField(max_length=100, null=True, verbose_name='Описание')),
                ('description_en', models.CharField(max_length=100, null=True, verbose_name='Описание')),
                ('description_ky', models.CharField(max_length=100, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.CreateModel(
            name='Stages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Stages/', verbose_name='Этапы строительства')),
            ],
            options={
                'verbose_name': 'Этап строительства',
                'verbose_name_plural': 'Этапы строительства',
            },
        ),
    ]
